export const sr = {
  brand: "KlikMoment",
  common: {
    save: "Sačuvaj",
    cancel: "Otkaži",
    back: "Nazad",
    next: "Dalje",
    loading: "Učitavanje...",
    error: "Došlo je do greške",
    success: "Uspešno",
  },
  nav: {
    home: "Početna",
    howItWorks: "Kako radi",
    packages: "Paketi",
    faq: "Pitanja",
    createGallery: "Kreiraj galeriju",
    signIn: "Prijava",
    signOut: "Odjava",
    dashboard: "Kontrolna tabla",
    events: "Događaji",
    users: "Korisnici",
    settings: "Podešavanja",
    myEvents: "Moji događaji",
  },
  landing: {
    heroTitle: "Vaši gosti će napraviti stotine slika. Koliko ćete vi od njih videti?",
    heroSubtitle:
      "Sve fotografije s proslave na jednom mestu — bez Vibera, bez čekanja, bez aplikacije.",
    heroCta: "Pošalji zahtev za galeriju",
    heroSecondary: "Pogledaj kako radi",
    trustLine: "Postavka za par minuta · Bez aplikacije · QR odmah spreman",
    slogan: "Uspomene koje ne sme da propadnu u chat grupi.",
    socialTitle: "Sa pravih proslava",
    socialSubtitle:
      "QR kodovi i galerije koje su gosti koristili na stvarnim događajima.",
    howTitle: "U tri jednostavna koraka",
    howSubtitle:
      "Sve je osmišljeno da bude brzo i lako, bez potrebe da bilo ko instalira aplikaciju.",
    steps: [
      { title: "Kreiraj", desc: "Popunite zahtev za par minuta i izaberite paket." },
      { title: "Podeli", desc: "Gosti skeniraju QR kod — bez registracije." },
      { title: "Uživaj", desc: "Slike i video stižu uživo; preuzmite sve jednim klikom." },
    ],
    packagesTitle: "Izaberite svoj paket",
    eventTypesTitle: "Odaberite vrstu događaja",
    eventTypesSubtitle: "Za svaku priliku",
    faqTitle: "Često postavljana pitanja",
    faqSubtitle: "Sve što vas zanima o KlikMoment digitalnim galerijama.",
  },
  faq: [
    {
      q: "Kako funkcioniše QR galerija?",
      a: "Gosti skeniraju QR kod na stolu i odmah mogu da pošalju fotografije i video snimke. Vi vidite sve u realnom vremenu.",
    },
    {
      q: "Da li gosti moraju da se registruju?",
      a: "Ne. Dovoljan je QR kod — bez aplikacije i bez naloga.",
    },
    {
      q: "Koliko dugo se čuvaju fotografije?",
      a: "Zavisi od paketa: od 30 do 180 dana. Detalje vidite u sekciji paketi.",
    },
    {
      q: "Da li je galerija javna ili privatna?",
      a: "Vi birate. U Premium i Profesionalnom paketu možete kontrolisati ko vidi galeriju.",
    },
    {
      q: "Kako se aktivira galerija nakon uplate?",
      a: "Nakon uplate, naš tim aktivira događaj u roku od 24h. Dobićete e-poštu sa pristupom.",
    },
  ],
  wizard: {
    stepCreate: "Kreiranje",
    stepPackage: "Izbor paketa",
    stepPayment: "Plaćanje",
    createTitle: "Kreirajte vaš događaj",
    createSubtitle: "Popunite detalje o vašem događaju",
    packageTitle: "Izaberite paket",
    packageSubtitle: "Odaberite paket i unesite kontakt podatke",
    eventName: "Naziv događaja",
    category: "Kategorija",
    eventDate: "Datum događaja",
    location: "Lokacija",
    welcomeMessage: "Poruka dobrodošlice",
    coverImage: "Naslovna slika (opciono)",
    coverHint: "Ova slika će biti prikazana na stranici za goste",
    uploadClick: "Kliknite da izaberete fajl",
    contactName: "Ime i prezime",
    contactEmail: "E-pošta",
    contactPhone: "Telefon",
    submitRequest: "Pošalji zahtev",
    continuePayment: "Pošalji zahtev",
    successTitle: "Zahtev je primljen!",
    successBody:
      "Proverite e-poštu — poslali smo vam uputstva za uplatu. Galerija će biti aktivirana nakon potvrde uplate.",
    placeholders: {
      eventName: "Proslava Petra — 30. jun",
      location: "Sala „Merkur“, Novi Sad",
      welcomeMessage: "Dobrodošli! Dodajte slike koje ste uslikali večeras.",
      ownerName: "Ana Jovanović",
      ownerEmail: "ana.jovanovic@gmail.com",
      ownerPhone: "+381 64 555 1234",
    },
    fillRequired: "Unesite naziv događaja i datum",
    contactSection: "Vaši podaci",
    selectPackage: "Paket",
  },
  guest: {
    sharePhotos: "Podelite svoje fotografije",
    gallery: "Galerija",
    yourName: "Vaše ime (opciono)",
    dropMedia: "Prevucite slike i video ovde",
    dropActive: "Spustite fajlove ovde",
    formats: "JPG, PNG, WEBP do 15 MB · MP4, MOV do 100 MB",
    eventEnded: "Ovaj događaj je završen. Slanje medija je isključeno.",
    pendingTitle: "Galerija se uskoro otvara",
    pendingBody: "Događaj čeka aktivaciju nakon uplate. Vratite se uskoro!",
    statusPending: "Na čekanju",
    statusUploading: "Šalje se...",
    statusDone: "Gotovo",
    statusError: "Greška",
  },
  auth: {
    signIn: "Prijava",
    email: "E-pošta",
    password: "Lozinka",
    showPassword: "Prikaži lozinku",
    hidePassword: "Sakrij lozinku",
    signingIn: "Prijavljivanje...",
    invalidCredentials: "Pogrešna e-pošta ili lozinka",
    activateTitle: "Aktivacija naloga",
    inactiveHint: "Prvo aktivirajte nalog putem linka iz e-pošte.",
  },
  admin: {
    createEvent: "Kreiraj događaj",
    updateEvent: "Ažuriraj događaj",
    saving: "Čuvanje...",
    pending: "Na čekanju",
    active: "Aktivni",
    expired: "Istekao",
    activateAfterPayment: "Aktiviraj nakon uplate",
    activated: "Događaj aktiviran",
    paymentSettings: "Podaci za uplatu",
    bankName: "Naziv banke",
    accountHolder: "Primalac",
    accountNumber: "Broj računa",
    paymentInstructions: "Dodatne instrukcije",
    referenceTemplate: "Šablon poziva na broj",
    settingsSaved: "Podešavanja sačuvana",
    dashboardTitle: "Admin kontrolna tabla",
    dashboardSubtitle: "Upravljanje događajima, korisnicima i platformom.",
    eventsCount: "Događaji",
    usersCount: "Korisnici",
    photosCount: "Fotografije",
    storageCount: "Prostor",
    editEvent: "Izmeni događaj",
    quickActions: "Brze akcije",
    eventSection: "Događaj",
    ownerSection: "Vlasnik",
    extend7Days: "Produži 7 dana",
    expireNow: "Istekni odmah",
    resetOwnerPassword: "Resetuj lozinku vlasnika",
    dangerZone: "Opasna zona",
    deleteEvent: "Obriši događaj",
    deleteConfirm:
      "Trajno obrisati ovaj događaj?\n\nBrišu se sve fotografije, prostor i nalog vlasnika ako nema drugih događaja.",
    eventDeleted: "Događaj obrisan",
    deleteFailed: "Brisanje nije uspelo",
    qrCode: "QR kod",
    publicPage: "Javna stranica",
    allZip: "Sve (ZIP)",
    gallery: "Galerija",
    activationEmailSent: "E-pošta za aktivaciju poslata",
    emailNotConfiguredCopied: "E-pošta nije podešena — link za aktivaciju kopiran",
    emailNotConfiguredCopy: "E-pošta nije podešena — kopirajte link iz obaveštenja",
    passwordReset: "Lozinka resetovana",
    failed: "Nije uspelo",
    eventDetails: "Detalji događaja",
    eventName: "Naziv događaja",
    description: "Opis",
    ownerEmail: "E-pošta vlasnika",
    settings: "Podešavanja",
    storageLimit: "Limit prostora (GB)",
    activeDays: "Aktivni dani",
    uploadsEnabled: "Slanje medija uključeno",
    viewEnabled: "Prikaz uključen",
    guestsCanView: "Gosti mogu da vide galeriju",
    guestsCanDownload: "Gosti mogu da preuzmu",
    saveFailed: "Čuvanje nije uspelo",
    eventCreatedEmailFailed: "Događaj kreiran — e-pošta nije poslata, link kopiran",
    eventCreatedEmailFailedNoCopy: "Događaj kreiran — e-pošta nije poslata",
    eventCreatedEmailSent: "Događaj kreiran — e-pošta za aktivaciju poslata",
    usersTitle: "Korisnici",
    usersSubtitle: "Upravljanje vlasnicima i adminima",
    resetPassword: "Resetuj lozinku",
    joined: "registrovan",
    photosLabel: "fotografija",
    ends: "do",
    roleAdmin: "Admin",
    roleOwner: "Vlasnik",
  },
  owner: {
    galleryTitle: "Galerija događaja",
    myEvents: "Moji događaji",
    myEventsSubtitle: "Upravljajte galerijama događaja",
    noEvents: "Nemate dodeljene događaje. Kontaktirajte administratora.",
    active: "Aktivan",
    coverImage: "Naslovna slika",
    photos: "Fotografije",
    storage: "Prostor",
    daysLeft: "Preostalo dana",
    expired: "Isteklo",
    storageUsage: "Iskorišćen prostor",
    percentUsed: "iskorišćeno",
    photosCount: "fotografija",
    ends: "do",
    chooseImage: "Izaberite sliku",
    uploadCover: "Pošalji naslovnu",
    replaceCover: "Zameni naslovnu",
    uploading: "Šalje se...",
    coverUploadFailed: "Slanje naslovne nije uspelo",
  },
  gallery: {
    noPhotos: "Još nema fotografija",
    noLikedPhotos: "Još nema omiljenih",
    noLikedHint: "Kliknite srce na fotografijama koje vam se dopadaju.",
    noPhotosHint: "Budite prvi koji deli uspomenu!",
    showLikedOnly: "Samo omiljene",
    showingLiked: "Prikazane omiljene",
    selectedZip: "Izabrane (ZIP)",
    allZip: "Sve (ZIP)",
    selectFirst: "Prvo izaberite fotografije",
    zipDownloaded: "Arhiva preuzeta",
    deletePhoto: "Obrisati ovu fotografiju?",
    photoDeleted: "Fotografija obrisana",
    deleteFailed: "Brisanje nije uspelo",
    likeFailed: "Ažuriranje omiljenog nije uspelo",
    viewFullSize: "Pogledaj u punoj veličini",
    likePhoto: "Dodaj u omiljene",
    unlikePhoto: "Ukloni iz omiljenih",
    downloadPhoto: "Preuzmi fotografiju",
    photoPreview: "Pregled fotografije",
    close: "Zatvori",
    previousPhoto: "Prethodna fotografija",
    nextPhoto: "Sledeća fotografija",
  },
  activate: {
    title: "Aktivirajte nalog",
    hint: "Postavite lozinku (min. 5 karaktera, 1 veliko slovo, 1 broj).",
    confirmPassword: "Potvrdite lozinku",
    activating: "Aktivacija...",
    activate: "Aktiviraj",
    success: "Nalog aktiviran! Molimo prijavite se.",
    failed: "Aktivacija nije uspela",
  },
  validation: {
    passwordMin: "Lozinka mora imati najmanje 5 karaktera",
    passwordUpper: "Lozinka mora sadržati bar jedno veliko slovo",
    passwordNumber: "Lozinka mora sadržati bar jedan broj",
    passwordsMismatch: "Lozinke se ne poklapaju",
    eventNameRequired: "Naziv događaja je obavezan",
    ownerEmailRequired: "Unesite ispravan email vlasnika",
  },
  editor: {
    font: "Font",
    size: "Veličina",
    linkUrl: "Unesite URL linka",
  },
  toast: {
    uploadFailed: "Slanje nije uspelo",
    saved: "Sačuvano",
    downloadFailed: "Preuzimanje nije uspelo",
    photoSaved: "Sačuvano",
    coverUpdated: "Naslovna slika ažurirana",
    eventCreated: "Događaj kreiran",
    eventUpdated: "Događaj ažuriran",
    requestSent: "Zahtev poslat — proverite e-poštu",
  },
} as const;

export type Sr = typeof sr;
